# -*- coding: utf-8 -*-
"""RAISE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZP8qoT2QtwdiN2aaDapR0pYH12qb4Mv

Team VPSync3
Hi! To access the code please downlaod all files in the VPSync3 Colab and upload them onto this colab to run the code and access all graphs. The files are: FILTERED_WITH_SENTIMENT.csv, data_centers_global.csv and GLOBAL_AI_NARRATIVES.csv
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from wordcloud import WordCloud
import plotly.graph_objects as go
import networkx as nx
import re
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.decomposition import PCA
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.manifold import TSNE
import matplotlib.patches as mpatches

df = pd.read_csv(f'/content/dataset_A_news_full_10500.csv')

"""

**Topics:- Human Roles, Social Interaction & Relationships, Society, Ethics & Culture**"""

df['class_list'] = df['classes_str'].str.split(';')
df_exploded = df.explode('class_list')

df_exploded['class_list'] = df_exploded['class_list'].str.strip()

df_exploded = df_exploded.rename(columns={'class_list': 'class_label'})

my_topics = ['Human Roles', 'Social Interaction & Relationships', 'Society, Ethics & Culture']
df_filtered = df_exploded[df_exploded['class_label'].isin(my_topics)]

df['class_list'] = df['classes_str'].str.split(';').apply(lambda x: [i.strip() for i in x])

all_classes = sorted(list(set([item for sublist in df['class_list'] for item in sublist])))

for cls in all_classes:
    df[cls] = df['class_list'].apply(lambda x: 1 if cls in x else 0)

correlation_matrix = df[all_classes].corr()

plt.figure(figsize=(12, 10))
mask = np.triu(np.ones_like(correlation_matrix, dtype=bool))

sns.heatmap(correlation_matrix,
            mask=mask,
            annot=True,
            fmt=".2f",
            cmap='coolwarm',
            center=0,
            square=True,
            linewidths=.5,
            cbar_kws={"shrink": .8})

plt.title("The 'Mirror' Effect: Co-occurrence of AI Behavioral Themes", fontsize=16)
plt.show()

try:
    from wordcloud import WordCloud, STOPWORDS

    social_keywords = ['social', 'friend', 'chat', 'relationship',
                      'companion', 'lonely', 'connect', 'community']

    social_mask = df['title'].apply(
        lambda x: any(keyword in x for keyword in social_keywords)
    )

    social_headlines = df[social_mask]

    if len(social_headlines) > 0:
        all_text = ' '.join(social_headlines['title'])

        stopwords = set(STOPWORDS)
        stopwords.update(['ai', 'artificial', 'intelligence', 'new',
                         'says', 'will', 'can', 'could', 'one'])

        plt.figure(figsize=(12, 8))
        wordcloud = WordCloud(
            width=1000,
            height=700,
            background_color='white',
            colormap='viridis',
            stopwords=stopwords,
            max_words=100,
            max_font_size=120,
            random_state=42
        ).generate(all_text)

        plt.imshow(wordcloud, interpolation='bilinear')
        plt.axis('off')
        plt.title(f'Word Cloud: Social AI Headlines\n({len(social_headlines)} headlines)',
                 fontsize=14, fontweight='bold', pad=20)

        from collections import Counter
        words = all_text.split()
        common_words = Counter([w for w in words if w not in stopwords and len(w) > 3])

        print(f"Total words analyzed: {len(words):,}")
        print("\nMost frequent terms (excluding common words):")
        for word, count in common_words.most_common(10):
            print(f"  '{word}': {count} times")

        plt.tight_layout()
        plt.show()

    else:
        print("No headlines found about social interaction")

except ImportError:
    print("Installing wordcloud library...")
    !pip install wordcloud
    print("Please re-run this cell")

emotion_lexicon = {
    'fear': ['fear', 'afraid', 'scared', 'terrified', 'anxious', 'worry', 'panic'],
    'anger': ['angry', 'outraged', 'furious', 'attack', 'war', 'fight'],
    'sadness': ['sad', 'depressed', 'tragic', 'loss', 'cry', 'mourn'],
    'joy': ['happy', 'joy', 'excited', 'celebrate', 'love', 'wonderful'],
    'trust': ['trust', 'reliable', 'safe', 'secure', 'confidence'],
    'surprise': ['surprise', 'shock', 'amazing', 'unexpected', 'breakthrough'],
    'disgust': ['disgust', 'horrible', 'evil', 'corrupt', 'manipulate'],
    'anticipation': ['expect', 'wait', 'coming', 'future', 'soon']
}

emotion_matrix = []
for title in df['title'].sample(1000, random_state=42):
    emotion_scores = {}
    for emotion, words in emotion_lexicon.items():
        score = sum(1 for word in words if word in title)
        emotion_scores[emotion] = score
    emotion_matrix.append(emotion_scores)

emotion_df = pd.DataFrame(emotion_matrix)


tsne = TSNE(n_components=2, random_state=42, perplexity=30)
emotion_2d = tsne.fit_transform(emotion_df)


from sklearn.cluster import DBSCAN
clusters = DBSCAN(eps=3, min_samples=5).fit_predict(emotion_2d)


plt.figure(figsize=(16, 10))


x = emotion_2d[:, 0]
y = emotion_2d[:, 1]


from scipy.stats import gaussian_kde
kde = gaussian_kde(np.vstack([x, y]))
xgrid, ygrid = np.mgrid[x.min():x.max():100j, y.min():y.max():100j]
zgrid = kde(np.vstack([xgrid.ravel(), ygrid.ravel()])).reshape(xgrid.shape)

contour = plt.contourf(xgrid, ygrid, zgrid, levels=15, cmap='viridis', alpha=0.6)
plt.colorbar(contour, label='Emotional Density')


for i, (xi, yi, cluster) in enumerate(zip(x, y, clusters)):
    if cluster != -1:
        dominant_emotion = emotion_df.iloc[i].idxmax()


        emotion_colors = {
            'fear': '#FF6B6B',
            'anger': '#C44D58',
            'sadness': '#6C5B7B',
            'joy': '#4ECDC4',
            'trust': '#45B7D1',
            'surprise': '#FFEAA5',
            'disgust': '#96CEB4',
            'anticipation': '#FFAF5F'
        }

        plt.scatter(xi, yi,
                   color=emotion_colors.get(dominant_emotion, 'gray'),
                   s=100, alpha=0.7, edgecolors='white', linewidth=0.5)

region_labels = {
    'Fear Zone': (-25, 15),
    'Hope Plateau': (15, 25),
    'Trust Valley': (-10, -20),
    'Anxiety Peaks': (20, -15),
    'Neutral Plains': (0, 0)
}

for label, (lx, ly) in region_labels.items():
    plt.annotate(label, xy=(lx, ly), xytext=(lx + np.random.uniform(-5, 5),
                                            ly + np.random.uniform(-5, 5)),
                fontsize=11, fontweight='bold',
                bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.8),
                arrowprops=dict(arrowstyle="->", color="black", alpha=0.6))


x_mountains = np.array([-20, 0, 20])
y_mountains = np.array([20, 25, 18])
plt.plot(x_mountains, y_mountains, '^', markersize=20, color='#FF6B6B', alpha=0.3)
plt.text(0, 27, "Emotional Peaks\n(High Intensity)", ha='center', fontweight='bold')


legend_elements = []
for emotion, color in emotion_colors.items():
    legend_elements.append(mpatches.Patch(color=color, label=emotion.title(), alpha=0.7))
plt.legend(handles=legend_elements, loc='upper right', fontsize=10, framealpha=0.9)


plt.title('Emotional Landscape of AI Media Coverage\nMapping the Psychological Terrain of Public Discourse',
          fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Narrative Dimension 1 (Fear ↔ Hope)', fontsize=12)
plt.ylabel('Narrative Dimension 2 (Trust ↔ Anxiety)', fontsize=12)
plt.grid(True, alpha=0.2, linestyle='--')

# Removed the problematic insight_text reference, as it's undefined and causing an error
# plt.figtext(0.02, 0.02, insight_text, fontsize=10,
#            bbox=dict(boxstyle="round,pad=0.5", facecolor="white", alpha=0.9))

plt.tight_layout()
plt.show()

"""**Topics:- Routine, Lifestyle & Behavior, Work, Jobs & Economy**"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import os

combined_df = pd.read_csv("/content/dataset_A_news_full_10500.csv")

combined_df['search_text'] = (combined_df['title'].astype(str) + " " +
                             combined_df.get('classes_str', '').astype(str)).str.lower()

categories = ['Job Loss', 'Productivity', 'Skills', 'Autonomy', 'Work-Life', 'Creativity']

impact_keywords = {
    'Job Loss': ['layoff', 'job loss', 'unemployment', 'replacement', 'redundant'],
    'Productivity': ['productivity', 'efficiency', 'output', 'automation', 'streamline'],
    'Skills': ['upskilling', 'training', 'learning', 'education', 'reskilling'],
    'Autonomy': ['autonomy', 'freedom', 'control', 'agency', 'decision making'],
    'Work-Life': ['work-life', 'well-being', 'balance', 'stress', 'burnout'],
    'Creativity': ['creativity', 'innovation', 'generative', 'art', 'design']
}

size = len(categories)
matrix = np.zeros((size, size))

masks = {cat: combined_df['search_text'].str.contains('|'.join(keywords), na=False)
         for cat, keywords in impact_keywords.items()}

for i in range(size):
    for j in range(size):
        if i == j:
            matrix[i, j] = 0
        else:
            count = (masks[categories[i]] & masks[categories[j]]).sum()
            matrix[i, j] = count

df_heatmap = pd.DataFrame(matrix, index=categories, columns=categories)

plt.figure(figsize=(11, 9))
sns.set_theme(style="white")

ax = sns.heatmap(
    df_heatmap,
    annot=True,
    fmt=".0f",
    cmap="YlOrRd",
    linewidths=2,
    linecolor='white',
    square=True,
    cbar_kws={'label': 'Co-occurrence Count'}
)

plt.title('Impact Correlations: What Happens Together?', fontsize=16, fontweight='bold', pad=25)
plt.xticks(rotation=0, fontsize=11)
plt.yticks(rotation=0, fontsize=11)

output_file = "/content/impact_correlation_heatmap.png"
plt.tight_layout()
plt.savefig(output_file, dpi=300)
plt.show()

"""**Topics:- Health, Safety & Risk, Cognitive & Decision-Making**"""

import torch
from transformers import pipeline
from tqdm import tqdm
device = 0 if torch.cuda.is_available() else -1
keywords = ["Health", "Safety", "Risk", "Cognitive", "Decision", "AI", "Intelligence"]
guardian_df = df[df['classes_str'].apply(lambda x: any(k in str(x) for k in keywords))].copy()

print(f"{len(guardian_df)} headlines.")

classifier = pipeline("zero-shot-classification",
                      model="facebook/bart-large-mnli",
                      device=device)
sentiment_analyzer = pipeline("sentiment-analysis",
                              model="distilbert-base-uncased-finetuned-sst-2-english",
                              device=device)
main_labels = [
    "Algorithmic Addiction & Social Isolation",
    "AI-Induced Anxiety & Dysmorphia",
    "Patient Safety Failure",
    "Loss of Human Control",
    "Systemic & Financial Risk",
    "General News or Positive"
]
results = []
scores = []
sentiments = []
sentiment_scores = []
for headline in tqdm(guardian_df['title']):
    try:
        prediction = classifier(headline, main_labels, hypothesis_template="This headline is about {}.")
        results.append(prediction['labels'][0])
        scores.append(prediction['scores'][0])

        sent_pred = sentiment_analyzer(headline)[0]
        sentiments.append(sent_pred['label'])
        sentiment_scores.append(sent_pred['score'])

    except Exception as e:
        results.append("Error")
        scores.append(0.0)
        sentiments.append("NEUTRAL")
        sentiment_scores.append(0.0)

guardian_df['Predicted_Risk'] = results
guardian_df['Confidence'] = scores
guardian_df['Sentiment_Label'] = sentiments
guardian_df['Sentiment_Score'] = sentiment_scores

sub_labels = [
    "Physical Kinetic Risk",
    "Economic Agentic Risk",
    "Information Decay Risk"
]
control_mask = guardian_df['Predicted_Risk'] == "Loss of Human Control"
control_subset = guardian_df[control_mask].copy()
sub_results = []
for headline in tqdm(control_subset['title']):
    try:
        pred = classifier(headline, sub_labels, hypothesis_template="This specific risk is {}.")
        sub_results.append(pred['labels'][0])
    except:
        sub_results.append("Unclassified")
guardian_df['Sub_Risk_Type'] = "Not Applicable"
guardian_df.loc[control_mask, 'Sub_Risk_Type'] = sub_results
output_filename = "health_risk_analysis.csv"
guardian_df.to_csv(output_filename, index=False)
print(f"'{output_filename}'")

plt.figure(figsize=(12, 6))
plot_df = guardian_df[guardian_df['Confidence'] > 0].copy()
order = plot_df.groupby('Predicted_Risk')['Confidence'].median().sort_values(ascending=False).index

sns.violinplot(x='Predicted_Risk', y='Confidence', data=plot_df,
               order=order, inner=None, palette="pastel", linewidth=0)

sns.stripplot(x='Predicted_Risk', y='Confidence', data=plot_df,
              order=order, color='k', size=2, alpha=0.4, jitter=True)

plt.title('Did Precision Improve? AI Confidence by Risk Type', fontsize=14)
plt.ylabel('Model Confidence (0-1)')
plt.xlabel('')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

file_path = "health_risk_analysis.csv"
df = pd.read_csv(file_path)
count_col = 'title' if 'title' in df.columns else ('url' if 'url' in df.columns else df.columns[0])

if 'Confidence' not in df.columns:
    df['Confidence'] = np.random.uniform(0.35, 0.50, size=len(df))

if 'Sentiment_Label' not in df.columns:
    df['Sentiment_Label'] = np.random.choice(['POSITIVE', 'NEGATIVE'], size=len(df))
    df['Sentiment_Score'] = np.random.uniform(0.1, 0.9, size=len(df))

def get_continuous_sentiment(row):
    score = row['Sentiment_Score']
    label = str(row['Sentiment_Label']).upper()
    return score if label == 'POSITIVE' else -score

df['Net_Sentiment'] = df.apply(get_continuous_sentiment, axis=1)

matrix = df.groupby('Predicted_Risk').agg({
    'Net_Sentiment': 'mean',
    'Confidence': 'mean',
    count_col: 'count'
}).reset_index()

matrix = matrix.rename(columns={count_col: 'Volume'})

plt.style.use('seaborn-v0_8-whitegrid')
plt.figure(figsize=(12, 8))

scatter = sns.scatterplot(
    data=matrix,
    x='Net_Sentiment',
    y='Confidence',
    size='Volume',
    hue='Predicted_Risk',
    sizes=(1000, 10000),
    alpha=0.75,
    edgecolor='black',
    linewidth=2,
    palette='Set1'
)

plt.axvline(0, color='grey', linestyle='--', alpha=0.5)
plt.axhline(matrix['Confidence'].mean(), color='grey', linestyle='--', alpha=0.5)

plt.title("The Risk Matrix: Separating Signal from Noise", fontsize=16, fontweight='bold', pad=20)
plt.xlabel("Sentiment (Left=Negative/Danger, Right=Positive/Safe)", fontsize=12)
plt.ylabel("AI Confidence (Top=Defined Risk, Bottom=Ambiguous)", fontsize=12)

plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left', title="Risk Category")

plt.tight_layout()
plt.show()

"""**Topics: Creativity, Expression & Identity, Learning, Knowledge & Education, Technology & Interaction**"""

import pandas as pd
import numpy as np
import re
import os
from collections import Counter
import glob
import plotly.graph_objects as go

def assign_region(country_name):
    country_lower = str(country_name).lower()
    europe_countries = [
        'united kingdom', 'uk', 'britain', 'england', 'scotland', 'wales',
        'france', 'germany', 'italy', 'spain', 'netherlands', 'belgium',
        'austria', 'switzerland', 'sweden', 'norway', 'denmark', 'finland',
        'poland', 'portugal', 'greece', 'ireland', 'czech republic', 'hungary',
        'romania', 'bulgaria', 'croatia', 'serbia', 'slovakia', 'slovenia',
        'estonia', 'latvia', 'lithuania', 'luxembourg', 'iceland', 'malta',
        'cyprus', 'moldova', 'belarus', 'ukraine', 'russia'
    ]

    asia_countries = [
        'china', 'japan', 'india', 'south korea', 'singapore', 'hong kong',
        'thailand', 'malaysia', 'indonesia', 'philippines', 'vietnam',
        'taiwan', 'bangladesh', 'pakistan', 'sri lanka', 'nepal', 'myanmar',
        'cambodia', 'laos', 'mongolia', 'kazakhstan', 'uzbekistan', 's. korea'
    ]
    americas_countries = [
        'united states', 'usa', 'us', 'canada', 'mexico', 'brazil', 'argentina',
        'chile', 'colombia', 'peru', 'venezuela', 'ecuador', 'uruguay',
        'paraguay', 'bolivia', 'panama', 'costa rica', 'guatemala',
        'dominican republic', 'cuba', 'jamaica', 'trinidad', 'barbados'
    ]
    mena_countries = [
        'saudi arabia', 'uae', 'united arab emirates', 'israel', 'turkey',
        'egypt', 'iran', 'iraq', 'jordan', 'lebanon', 'kuwait', 'qatar',
        'bahrain', 'oman', 'yemen', 'syria', 'morocco', 'algeria', 'tunisia'
    ]
    oceania_countries = [
        'australia', 'new zealand', 'nz', 'fiji', 'papua new guinea'
    ]
    africa_countries = [
        'south africa', 'kenya', 'nigeria', 'ghana', 'ethiopia', 'tanzania',
        'uganda', 'senegal', 'cameroon', 'ivory coast', 'zimbabwe', 'zambia',
        'mozambique', 'madagascar', 'angola', 'botswana', 'namibia'
    ]
    for country_list, region in [
        (oceania_countries, 'Oceania'),
        (europe_countries, 'Europe'),
        (asia_countries, 'Asia'),
        (americas_countries, 'Americas'),
        (mena_countries, 'Middle East/North Africa'),
        (africa_countries, 'Africa')
    ]:
        if any(c in country_lower for c in country_list):
            return region

    return 'Other'


REGION_COLORS = {
    'Europe': '#964B00',
    'Asia': '#f1c40f',
    'Americas': '#FFA500',
    'Middle East/North Africa': '#3498db',
    'Oceania': '#9b59b6',
    'Africa': '#808080',
    'Other': '#95a5a6'
}


def _scale(v, out_min, out_max):
    v = np.asarray(v, dtype=float)
    if len(v) == 0:
        return v
    vmin, vmax = np.min(v), np.max(v)
    if vmax == vmin:
        return np.full_like(v, (out_min + out_max) / 2.0)
    return out_min + (v - vmin) * (out_max - out_min) / (vmax - vmin)

def bezier_curve(p0, p1, c, n=40):
    t = np.linspace(0, 1, n)
    x = (1-t)**2*p0[0] + 2*(1-t)*t*c[0] + t**2*p1[0]
    y = (1-t)**2*p0[1] + 2*(1-t)*t*c[1] + t**2*p1[1]
    return x, y

possible_article_paths = [
    'FILTERED_WITH_SENTIMENT.csv',
    'scraped_articles_COMPLETE.csv',
    '/content/drive/MyDrive/RAISE_Project/FILTERED_WITH_SENTIMENT.csv',
    '/content/drive/MyDrive/FILTERED_WITH_SENTIMENT.csv',
    '/content/sample_data/FILTERED_WITH_SENTIMENT.csv',
    '/content/drive/MyDrive/untitled folder/Raise group/mapcreationhtmlfile/FILTERED_WITH_SENTIMENT.csv',
    *glob.glob('*FILTERED*.csv'),
    *glob.glob('*scraped*.csv'),
]

df = None
for path in possible_article_paths:
    if os.path.exists(path):
        df = pd.read_csv(path)
        print(f"Found: {path}")
        break

if df is None:
    raise FileNotFoundError("Could not find articles CSV file")

print(f"✓ Loaded {len(df):,} articles")

country_cols = ['country', 'Country', 'country_norm']
country_col = None
for col in country_cols:
    if col in df.columns:
        country_col = col
        break

if country_col is None:
    raise ValueError(f"Could not find country column! Available: {list(df.columns)}")
else:
    if country_col != 'country':
        df['country'] = df[country_col]

if 'title' not in df.columns:
    raise ValueError("'title' column not found! Cannot extract keywords from headlines.")
df['headline_text'] = df['title'].fillna('')
print(f"Using HEADLINES ONLY for keyword extraction")

df['region'] = df['country'].apply(assign_region)
region_counts = df['region'].value_counts()
print(f"✓ Assigned regions:")
for region, count in region_counts.items():
    print(f"  {region:30s}: {count:6d} articles ({count/len(df)*100:.1f}%)")

def extract_keywords(text, keywords):
    if pd.isna(text) or not isinstance(text, str) or text == '':
        return []
    text_lower = str(text).lower()
    found_keywords = []
    for kw in keywords:
        if re.search(rf'\b{re.escape(kw)}', text_lower):
            found_keywords.append(kw)
    return list(set(found_keywords))

def run_visualization(
    df_source,
    text_col,
    integration_keywords,
    control_keywords,
    title_suffix,
    output_html,
    summary_prefix
):

    all_keywords = integration_keywords + control_keywords
    df_local = df_source.copy()
    df_local['found_keywords'] = df_local[text_col].apply(lambda x: extract_keywords(x, all_keywords))

    keyword_counts = Counter()
    for keywords_list in df_local['found_keywords']:
        keyword_counts.update(keywords_list)

    top_control = [(kw, keyword_counts.get(kw, 0)) for kw in control_keywords]
    top_integration = [(kw, keyword_counts.get(kw, 0)) for kw in integration_keywords]
    top_keywords = top_control + top_integration

    print(f"✓ Selected {len(top_keywords)} keywords for visualization: "
          f"{len(top_control)} control/risk + {len(top_integration)} integration")

    print("\nSummary Statistics")
    print(f"Top {len(integration_keywords)} integration (with counts):")
    for kw, count in top_integration:
        print(f"  {kw}: {count}")
    print(f"Top {len(control_keywords)} control/risk (with counts):")
    for kw, count in top_control:
        print(f"  {kw}: {count}")

    country_normalization = {
        'USA': 'United States',
        'US': 'United States',
        'U.S.': 'United States',
        'U.S.A.': 'United States',
        'United States of America': 'United States',
        'America': 'United States',
        'UK': 'United Kingdom',
        'S. Korea': 'South Korea',
        'South Korea': 'South Korea',
        'NZ': 'New Zealand',
        'UAE': 'United Arab Emirates',
    }

    df_local['country_normalized'] = df_local['country'].map(lambda x: country_normalization.get(x, x))

    TOP_N_COUNTRIES = 40
    top_countries_raw = df_local['country_normalized'].value_counts().head(TOP_N_COUNTRIES).index.tolist()
    df_filtered = df_local[df_local['country_normalized'].isin(top_countries_raw)].copy()

    edges_list = []
    for country in top_countries_raw:
        country_df = df_filtered[df_filtered['country_normalized'] == country]

        country_keyword_counts = Counter()
        for keywords_list in country_df['found_keywords']:
            country_keyword_counts.update(keywords_list)

        for keyword, _ in top_keywords:
            if country_keyword_counts.get(keyword, 0) > 0:
                edges_list.append({
                    'outer': country,
                    'inner': keyword,
                    'weight': country_keyword_counts[keyword]
                })

    edge_df = pd.DataFrame(edges_list)

    if len(edge_df) == 0:
        raise ValueError("No connections found! Check your data.")

    countries_with_keywords = set(edge_df['outer'].unique())

    keyword_colors = {}
    for keyword, _ in top_keywords:
        if keyword in integration_keywords:
            keyword_colors[keyword] = '#2ecc71'
        else:
            keyword_colors[keyword] = '#e74c3c'

    outer_colors = {}
    for country in countries_with_keywords:
        region = assign_region(country)
        outer_colors[country] = REGION_COLORS.get(region, '#95a5a6')

    inner_positions = {}
    angles = np.linspace(0, 2*np.pi, len(top_keywords), endpoint=False)
    r = 0.50
    for i, (keyword, _) in enumerate(top_keywords):
        inner_positions[keyword] = (r * np.cos(angles[i]), r * np.sin(angles[i]))

    edge_df['region'] = edge_df['outer'].apply(assign_region)
    edge_df['region_color'] = edge_df['region'].map(REGION_COLORS)

    dominant = (edge_df.groupby(['outer', 'inner'])['weight'].sum()
                .reset_index()
                .sort_values(['outer', 'weight'], ascending=[True, False])
                .drop_duplicates(subset=['outer'])
                .rename(columns={'inner': 'dominant_keyword'}))

    outer_totals = edge_df.groupby('outer')['weight'].sum().rename('outer_total').reset_index()
    dom = dominant.merge(outer_totals, on='outer', how='left')
    dom = dom.merge(edge_df[['outer', 'region_color']].drop_duplicates(), on='outer', how='left')

    dom = dom.sort_values(['region_color', 'dominant_keyword', 'outer_total'],
                          ascending=[True, True, False])
    outer_nodes_ordered = dom['outer'].tolist()

    angles = np.linspace(0, 2*np.pi, len(outer_nodes_ordered), endpoint=False)
    outer_positions = {n: (1.08*np.cos(a), 1.08*np.sin(a), a) for n, a in zip(outer_nodes_ordered, angles)}

    inner_nodes = list(inner_positions.keys())
    inner_totals = edge_df.groupby('inner')['weight'].sum().reindex(inner_nodes).fillna(0).values
    outer_totals_arr = []
    for c in outer_nodes_ordered:
        total = edge_df.loc[edge_df['outer'] == c, 'weight'].sum()
        outer_totals_arr.append(total)

    inner_sizes = _scale(inner_totals, 15, 50)
    edge_widths = _scale(edge_df['weight'].values, 0.5, 5)

    fig = go.Figure()

    for (idx, row), lw in zip(edge_df.iterrows(), edge_widths):
        country = row['outer']
        keyword = row['inner']
        weight = row['weight']

        if country not in outer_positions or keyword not in inner_positions:
            continue

        x0, y0, a0 = outer_positions[country]
        x1, y1 = inner_positions[keyword]

        cx = 0.08*np.cos(a0) + 0.18*x1
        cy = 0.08*np.sin(a0) + 0.18*y1

        x_curve, y_curve = bezier_curve((x0, y0), (x1, y1), (cx, cy), n=45)

        hover_text = f"<b>{keyword.title()}</b> → <b>{country}</b><br>Articles: {int(weight):,}"

        fig.add_trace(go.Scatter(
            x=x_curve,
            y=y_curve,
            mode='lines',
            line=dict(width=float(lw), color=keyword_colors.get(keyword, '#999999')),
            opacity=0.25,
            hoverinfo='text',
            hovertext=hover_text,
            showlegend=False
        ))

    inner_x = [inner_positions[k][0] for k in inner_nodes]
    inner_y = [inner_positions[k][1] for k in inner_nodes]
    inner_text = [k for k in inner_nodes]
    inner_hover = [
        f"<b>{k}</b><br>Articles: {int(edge_df.loc[edge_df['inner'] == k, 'weight'].sum()):,}<br>"
        f"Category: {'Integration' if k in integration_keywords else 'Control/Risk'}"
        for k in inner_nodes
    ]

    fig.add_trace(go.Scatter(
        x=inner_x,
        y=inner_y,
        mode='markers+text',
        marker=dict(
            size=inner_sizes,
            color=[keyword_colors.get(k, '#95a5a6') for k in inner_nodes],
            line=dict(width=2, color='white'),
            opacity=0.9
        ),
        text=inner_text,
        textposition='middle center',
        textfont=dict(size=11, color='black', family='Arial Black'),
        hovertext=inner_hover,
        hoverinfo='text',
        name='Keywords',
        showlegend=False
    ))

    outer_x = [outer_positions[c][0] for c in outer_nodes_ordered]
    outer_y = [outer_positions[c][1] for c in outer_nodes_ordered]
    all_outer_totals = []
    for c in outer_nodes_ordered:
        total = edge_df.loc[edge_df['outer'] == c, 'weight'].sum()
        all_outer_totals.append(total)

    all_outer_sizes = _scale(np.log1p(all_outer_totals), 6, 90)
    outer_hover = []
    for c in outer_nodes_ordered:
        total = int(edge_df.loc[edge_df['outer'] == c, 'weight'].sum())
        hover_text = f"<b>{c}</b><br>Region: {assign_region(c)}<br>Total articles: {total:,}"
        outer_hover.append(hover_text)

    fig.add_trace(go.Scatter(
        x=outer_x,
        y=outer_y,
        mode='markers',
        marker=dict(
            size=all_outer_sizes,
            color=[outer_colors.get(c, '#95a5a6') for c in outer_nodes_ordered],
            line=dict(width=1.5, color='white'),
            opacity=0.95
        ),
        hovertext=outer_hover,
        hoverinfo='text',
        name='Countries',
        showlegend=False
    ))

    for country in outer_nodes_ordered:
        x, y, angle = outer_positions[country]
        label_x = x * 1.12
        label_y = y * 1.12

        label_text = country
        if len(country) > 15:
            abbreviations = {
                'United States': 'USA',
                'United Kingdom': 'UK',
                'United Arab Emirates': 'UAE',
                'South Korea': 'S. Korea',
                'New Zealand': 'NZ',
                'South Africa': 'S. Africa',
            }
            label_text = abbreviations.get(country, country[:15])

        fig.add_annotation(
            x=label_x,
            y=label_y,
            text=label_text,
            showarrow=False,
            font=dict(size=8, color='black', family='Arial'),
            bgcolor='rgba(255, 255, 255, 0.7)',
            bordercolor='gray',
            borderwidth=0.5,
            borderpad=2,
            xanchor='center',
            yanchor='middle'
        )

    title_text = (
        f"Radial Bubble Network ({title_suffix})<br>"
    )

    fig.update_layout(
        title={
            'text': title_text,
            'x': 0.5,
            'xanchor': 'center',
            'font': {'size': 16}
        },
        showlegend=False,
        hovermode='closest',
        margin=dict(b=40, l=40, r=280, t=100),
        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False, scaleanchor='y'),
        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        plot_bgcolor='white',
        height=1000,
        width=1000
    )
    fig.update_yaxes(scaleanchor='x', scaleratio=1)

    legend_text = """
<b>Legend:</b><br>
• Inner bubbles = Keywords<br>
  🟢 Green = Integration<br>
  🔴 Red = Control/Risk<br>
• Outer ring = Countries<br>
  🟤 Europe<br>
  🟡 Asia<br>
  🟠 Americas<br>
  🔵 Middle East/N.Africa<br>
  🟣 Oceania<br>
  ⭕ Africa<br>
• Lines = Connections<br>
  (thickness = frequency)
"""

    fig.add_annotation(
        x=1.25, y=0.5,
        xref='paper', yref='paper',
        text=legend_text,
        showarrow=False,
        align='left',
        bgcolor='rgba(255, 255, 255, 0.9)',
        bordercolor='gray',
        borderwidth=1,
        font=dict(size=10)
    )

    fig.write_html(output_html)

    df_filtered['region'] = df_filtered['country_normalized'].apply(assign_region)
    region_summary = df_filtered.groupby('region').agg({
        'country_normalized': 'nunique',
        'title': 'count'
    }).reset_index()
    region_summary.columns = ['region', 'countries', 'articles']
    region_summary['region_color'] = region_summary['region'].map(REGION_COLORS)
    region_summary = region_summary.sort_values('articles', ascending=False)
    region_summary.to_csv(f'regional_summary_{summary_prefix}.csv', index=False)

    edge_summary = edge_df.copy()
    edge_summary['keyword_category'] = edge_summary['inner'].map(
        lambda x: 'Integration' if x in integration_keywords else 'Control/Risk'
    )
    edge_summary = edge_summary.sort_values(['outer', 'weight'], ascending=[True, False])
    edge_summary.to_csv(f'country_keyword_connections_regions_{summary_prefix}.csv', index=False)

    return fig

INTEGRATION_KEYWORDS_ARTICLES = [
    "data", "technology", "students", "tools",
    "research", "education", "learning", "digital"
]
CONTROL_KEYWORDS_ARTICLES = ["security", "risk"]

INTEGRATION_KEYWORDS_HEADLINES = [
    "study", "innovation", "education", "technology",
    "digital", "learning", "adoption", "training"
]
CONTROL_KEYWORDS_HEADLINES = ["risk", "ethical"]

run_visualization(
    df_source=df,
    text_col='headline_text',
    integration_keywords=INTEGRATION_KEYWORDS_HEADLINES,
    control_keywords=CONTROL_KEYWORDS_HEADLINES,
    title_suffix='Headlines Only',
    output_html='keywords_countries_regions_articles.html',
    summary_prefix='headlines'
)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')
try:
    plt.style.use('seaborn-v0_8-darkgrid')
except:
    try:
        plt.style.use('seaborn-darkgrid')
    except:
        plt.style.use('ggplot')
sns.set_palette("husl")

print("AI Release Timeline vs Media Attention")
possible_paths = [
    'FILTERED_WITH_SENTIMENT.csv',
    'mapcreationhtmlfile/FILTERED_WITH_SENTIMENT.csv',
    '/content/drive/MyDrive/RAISE_Project/FILTERED_WITH_SENTIMENT.csv',
    '/content/drive/MyDrive/FILTERED_WITH_SENTIMENT.csv',
    '/content/sample_data/FILTERED_WITH_SENTIMENT.csv',
]
df = None
for path in possible_paths:
    try:
        df = pd.read_csv(path)
        break
    except FileNotFoundError:
        continue

if df is None:
    exit(1)

date_col = 'article_date' if 'article_date' in df.columns else 'date'
if date_col not in df.columns:
    raise ValueError("No date column found ('article_date' or 'date').")
df['date'] = pd.to_datetime(df[date_col], errors='coerce', utc=True)
df['date'] = df['date'].dt.tz_convert(None)
df = df[df['date'].notna()].copy()
if df.empty:
    raise ValueError("No valid dates found after parsing.")
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['quarter'] = df['date'].dt.quarter

focus_classes = [
    "Technology & Interaction",
    "Learning, Knowledge & Education",
    "Creativity, Expression & Identity"
]

keywords = ["Technology", "Interaction", "Learning", "Knowledge", "Education",
            "Creativity", "Expression", "Identity"]

if 'classes_str' in df.columns:
    df_focus = df[df['classes_str'].apply(lambda x: any(k in str(x) for k in keywords))].copy()
else:
    df_focus = df.copy()

ai_releases = [
    {"date": "2025-01-20", "name": "DeepSeek R1", "company": "DeepSeek", "importance": "high"},
    {"date": "2025-02-27", "name": "GPT-4.5", "company": "OpenAI", "importance": "high"},
    {"date": "2025-03-25", "name": "Gemini 2.5", "company": "Google", "importance": "high"},
    {"date": "2025-04-05", "name": "Llama 4", "company": "Meta", "importance": "high"},
    {"date": "2025-04-30", "name": "Nova 1.0 Premier", "company": "Amazon", "importance": "medium"},
    {"date": "2025-05-20", "name": "Veo 3", "company": "Google", "importance": "medium"},
    {"date": "2025-05-22", "name": "Claude 4", "company": "Anthropic", "importance": "high"},
    {"date": "2025-06-18", "name": "Midjourney V1 Video", "company": "Midjourney", "importance": "medium"},
    {"date": "2025-06-25", "name": "Gemini CLI", "company": "Google", "importance": "medium"},
    {"date": "2025-07-07", "name": "Azure Foundry Agent Service", "company": "Microsoft", "importance": "medium"},
    {"date": "2025-07-09", "name": "Grok 4", "company": "xAI", "importance": "high"},
    {"date": "2025-07-17", "name": "ChatGPT Agent", "company": "OpenAI", "importance": "high"},
    {"date": "2025-07-28", "name": "GLM-4.5", "company": "Zhipu", "importance": "high"},
    {"date": "2025-08-05", "name": "Claude Opus 4.1", "company": "Anthropic", "importance": "high"},
    {"date": "2025-08-20", "name": "DeepSeek-V3.1", "company": "DeepSeek", "importance": "high"},
    {"date": "2025-08-25", "name": "Nano Banana", "company": "Google", "importance": "medium"},
    {"date": "2025-08-07", "name": "GPT-5", "company": "OpenAI", "importance": "very_high"},
    {"date": "2025-09-09", "name": "Veo 3 + NVIDIA AI Chips", "company": "Google/NVIDIA", "importance": "high"},
    {"date": "2025-09-30", "name": "Sora 2 + Social App", "company": "OpenAI", "importance": "very_high"},
    {"date": "2025-10-15", "name": "Claude Haiku 4.5", "company": "Anthropic", "importance": "medium"},
    {"date": "2025-11-17", "name": "Grok 4.1", "company": "xAI", "importance": "high"},
    {"date": "2025-11-18", "name": "Gemini 3", "company": "Google", "importance": "very_high"},
    {"date": "2025-11-24", "name": "Claude Opus 4.5", "company": "Anthropic", "importance": "high"},
    {"date": "2025-12-11", "name": "GPT-5.2", "company": "OpenAI", "importance": "very_high"},
]

releases_df = pd.DataFrame(ai_releases)
releases_df['date'] = pd.to_datetime(releases_df['date'])
releases_df = releases_df[releases_df['date'].dt.year == 2025].copy()

df_focus['date_only'] = df_focus['date'].dt.date
daily_attention = df_focus.groupby('date_only').size().reset_index(name='headlines')
daily_attention['date'] = pd.to_datetime(daily_attention['date_only'])

daily_attention = daily_attention.sort_values('date')
daily_attention['rolling_avg'] = daily_attention['headlines'].rolling(window=7, center=True).mean()
daily_attention['rolling_avg'] = daily_attention['rolling_avg'].fillna(daily_attention['headlines'])

start_2025 = pd.Timestamp('2025-01-01')
end_2025 = pd.Timestamp('2025-12-31')
daily_attention = daily_attention[(daily_attention['date'] >= start_2025) & (daily_attention['date'] <= end_2025)]

print("\nCreating timeline visualization...")

def plot_timeline(ax, title_suffix, x_start, x_end, use_single_release_color=False):
    ax.fill_between(daily_attention['date'], 0, daily_attention['headlines'],
                    alpha=0.3, color='steelblue', label='Daily Headlines (All AI)')
    ax.plot(daily_attention['date'], daily_attention['rolling_avg'],
            color='darkblue', linewidth=2.5, label='7-Day Rolling Avg (All AI)')
    importance_colors = {
        'very_high': '#FF0000',
        'high': '#FF6B00',
        'medium': '#FFA500'
    }
    single_release_color = '#FF8C00'

    releases_window = releases_df[
        (releases_df['date'] >= x_start) & (releases_df['date'] <= x_end)
    ].copy()
    for idx, release in releases_window.iterrows():
        if use_single_release_color:
            color = single_release_color
            linewidth = 2
        else:
            color = importance_colors.get(release['importance'], '#808080')
            linewidth = 3 if release['importance'] == 'very_high' else 2 if release['importance'] == 'high' else 1.5

        ax.axvline(x=release['date'], color=color, linestyle='--',
                   linewidth=linewidth, alpha=0.7, zorder=5)

        max_y = daily_attention['headlines'].max()
        y_pos = max_y * (0.85 - (idx % 3) * 0.1)
        label_text = f"{release['company']}: {release['name']}"
        ax.text(release['date'], y_pos, label_text,
                rotation=90, ha='right', va='bottom', fontsize=8,
                bbox=dict(boxstyle='round,pad=0.3', facecolor='white',
                          edgecolor=color, alpha=0.8, linewidth=1.5))

    ax.set_xlabel('Date', fontsize=12, fontweight='bold')
    ax.set_ylabel('Number of Headlines (Media Attention)', fontsize=12, fontweight='bold')
    ax.set_title(f'Media Attention Over Time with AI Model Releases ({title_suffix})',
                 fontsize=14, fontweight='bold', pad=15)
    ax.legend(loc='upper left', fontsize=10)
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.set_xlim(x_start, x_end)

    if title_suffix == "2025":
        for q in [1, 2, 3, 4]:
            quarter_start = pd.Timestamp(f'2025-{(q-1)*3+1:02d}-01')
            ax.axvline(x=quarter_start, color='gray', linestyle=':',
                       linewidth=1, alpha=0.3, zorder=1)
            ax.text(quarter_start, ax.get_ylim()[1] * 0.95, f'Q{q}',
                    ha='center', fontsize=9, color='gray', fontweight='bold',
                    bbox=dict(boxstyle='round', facecolor='lightgray', alpha=0.5))

fig, ax1 = plt.subplots(1, 1, figsize=(18, 8))
fig.suptitle('AI Release Timeline vs Media Attention "Hype" (2025)',
             fontsize=18, fontweight='bold', y=0.98)
plot_timeline(ax1, "2025", start_2025 - pd.Timedelta(days=5), end_2025 + pd.Timedelta(days=5))
plt.tight_layout()
plt.savefig('ai_release_timeline.png', dpi=300, bbox_inches='tight')
print("Saved ai_release_timeline.png")

focus_start = pd.Timestamp('2025-06-01')
focus_end = pd.Timestamp('2025-10-01')
fig, ax_focus = plt.subplots(1, 1, figsize=(18, 8))
fig.suptitle('AI Release Timeline vs Media Attention "Hype" (Jun - Sep 2025)',
             fontsize=18, fontweight='bold', y=0.98)
plot_timeline(ax_focus, "Jun–Sep 2025", focus_start, focus_end)
plt.tight_layout()
plt.savefig('ai_release_timeline_focus.png', dpi=300, bbox_inches='tight')
print("Saved ai_release_timeline_focus.png")

fig, ax_focus_orange = plt.subplots(1, 1, figsize=(18, 8))
fig.suptitle('AI Release Timeline vs Media Attention "Hype" (Jun - Sep 2025)',
             fontsize=18, fontweight='bold', y=0.98)
plot_timeline(ax_focus_orange, "Jun–Sep 2025", focus_start, focus_end, use_single_release_color=True)
plt.tight_layout()
plt.savefig('ai_release_timeline_focus_orange.png', dpi=300, bbox_inches='tight')
print("Saved ai_release_timeline_focus_orange.png")

"""

**Topics: - Sentiment, Emotion, Motivation & Well-being**"""

!apt-get install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh


import subprocess
import time
import os


subprocess.Popen(['ollama', 'serve'])


time.sleep(10)


!ollama pull llama3.2


!pip install ollama

import pandas as pd

print("Loading original dataset...")
df = pd.read_csv('dataset_A_news_full_10500.csv')


filter_condition = df['classes_str'].str.contains('Sentiment|Emotion', case=False, na=False)

filtered_df = df[filter_condition].copy()


original_count = len(df)
filtered_count = len(filtered_df)
print(f"Filtering Complete!")
print(f"Original Articles: {original_count}")
print(f"Articles with 'Sentiment' or 'Emotion': {filtered_count}")


filtered_df.to_csv('FILTERED_EMOTION_DATA.csv', index=False)
print("Saved to 'FILTERED_EMOTION_DATA.csv'")

import pandas as pd
from ollama import chat
import sys

file_path = 'FILTERED_EMOTION_DATA.csv'
try:
    df = pd.read_csv(file_path)
    print(f"Successfully loaded {len(df)} articles.")
except FileNotFoundError:
    print(f"Error: {file_path} not found.")
    sys.exit()

def generate_ai_summary(title):
    """Sends a single title to Ollama to get a one-sentence summary."""
    prompt = f"""
    TASK: Write a one-sentence, insightful summary of this news title.
    Stay factual but make it engaging for a report.

    TITLE: "{title}"

    SUMMARY:
    """

    try:
        response = chat(model='llama3.2', messages=[{'role': 'user', 'content': prompt}])
        summary = response.message.content.strip().replace('"', '')
        return summary
    except Exception as e:
        return f"Error generating summary: {e}"

print("Consulting AI for summaries (this may take a moment per row)...")

df['one_sentence_summary'] = df['title'].apply(generate_ai_summary)

output_file = 'ENRICHED_NEWS_DATA.csv'
df.to_csv(output_file, index=False)

print("-" * 30)
print(f"DONE! Enriched data saved to: {output_file}")
print("Preview of summaries:")
print(df[['title', 'one_sentence_summary']].head())

import pandas as pd
import ollama
from tqdm import tqdm

df = pd.read_csv('ENRICHED_NEWS_DATA.csv')

def get_sentiment_strict(text):
    if pd.isna(text) or text.strip() == "": return "Neutral"

    prompt = f"""
    You are a highly sensitive Sentiment Analyst.
    Classify the HUMAN IMPACT of this news summary as Positive, Negative, or Neutral.

    EXAMPLES:
    - "AI improves cancer detection rates by 30%" -> Positive
    - "AI-generated deepfakes are used to bully students" -> Negative
    - "The company released its quarterly AI report on Tuesday" -> Neutral

    STRICT RULES:
    1. If there is ANY risk, harm, or fear, you MUST choose 'Negative'.
    2. If there is ANY benefit, progress, or joy, you MUST choose 'Positive'.
    3. Output ONLY the word: Positive, Negative, or Neutral.

    SUMMARY: {text}
    """
    try:
        res = ollama.chat(
            model='llama3.2',
            messages=[{'role': 'user', 'content': prompt}],
            options={'temperature': 0}
        )
        answer = res['message']['content'].strip().replace('.', '').capitalize()
        if "Positive" in answer: return "Positive"
        if "Negative" in answer: return "Negative"
        return "Neutral"
    except:
        return "Neutral"

print("Running Sentiment Analysis on 'one_sentence_summary'...")
tqdm.pandas()
df['sentiment'] = df['one_sentence_summary'].progress_apply(get_sentiment_strict)

print("\nCurrent Sentiment Breakdown:")
print(df['sentiment'].value_counts())

df.to_csv('SENTIMENT_DATA.csv', index=False)

import pandas as pd
import ollama
import json

df = pd.read_csv('SENTIMENT_DATA.csv')

def get_middle_ground_themes(sentiment_type):
    subset = df[df['sentiment'] == sentiment_type]['one_sentence_summary']
    samples = "- " + "\n- ".join(subset.sample(min(250, len(subset))).tolist())

    prompt = f"""
    Analyze these news summaries regarding {sentiment_type} AI impacts.
    Identify 5 DISTINCT and SPECIFIC societal narratives.

    CRITICAL RULES:
    1. AVOID BROAD BUCKETS: Do not use 'Ethics', 'General Progress', 'Regulation', or 'Innovation'.
    2. THE SWEET SPOT: Themes must be specific enough to describe a real problem/benefit (e.g., 'Replacement of entry-level administrative roles') but general enough to apply to multiple different companies/locations.
    3. NO PROPER NOUNS: No names of companies, cities, or specific people.
    4. HUMAN-CENTRIC: Focus on how a person's life, job, or safety changes.
    DATA:
    {samples}

    Respond ONLY with a JSON object:
    {{
      "narratives": [
        {{"theme": "Theme Title", "description": "1-sentence explanation of why this trend is {sentiment_type}."}},
        ... (exactly 5)
      ]
    }}
    """

    res = ollama.chat(model='llama3.2', messages=[{'role': 'user', 'content': prompt}], format='json')
    data = json.loads(res['message']['content'])

    for item in data['narratives']:
        item['sentiment_group'] = sentiment_type

    return data['narratives']

print("Distilling 500 articles into 10 key narratives...")
neg_results = get_middle_ground_themes('Negative')
pos_results = get_middle_ground_themes('Positive')

final_narratives_df = pd.DataFrame(neg_results + pos_results)

final_narratives_df.to_csv('AI_NARRATIVE_REPORT.csv', index=False)

print("\nNARRATIVE REPORT CREATED!")
print("-" * 30)
print(final_narratives_df[['sentiment_group', 'theme', 'description']])

import pandas as pd
import ollama
import re
from tqdm import tqdm

tqdm.pandas()

df = pd.read_csv('SENTIMENT_DATA.csv')
report_df = pd.read_csv('AI_NARRATIVE_REPORT.csv')

pos_options = report_df[report_df['sentiment_group'] == 'Positive'].to_dict('records')
neg_options = report_df[report_df['sentiment_group'] == 'Negative'].to_dict('records')

def label_with_sentiment_context(row):
    title = str(row.get('title', ''))
    summary = str(row.get('one_sentence_summary', ''))
    sentiment = row.get('sentiment', 'Neutral')

    current_themes = pos_options if sentiment == 'Positive' else neg_options

    if sentiment == 'Neutral' or not current_themes:
        return "Neutral/Other", "Neutral"

    options_text = ""
    for i, t in enumerate(current_themes):
        options_text += f"{i}: {t['theme']} - {t['description']}\n"

    prompt = f"""
    [INST]
    Analyze this AI news article. Use the Title and Summary to pick the best Category.
    TITLE: {title}
    SUMMARY: {summary}
    VALID CATEGORIES ({sentiment}):
    {options_text}
    TASK: Rank the TOP 3 most relevant category numbers.
    Format:
    Rank 1: [number]
    Rank 2: [number]
    Rank 3: [number]
    [/INST]
    """

    try:
        res = ollama.chat(model='llama3.2', messages=[{'role': 'user', 'content': prompt}], options={'temperature': 0})
        response = res['message']['content']

        match = re.search(r'Rank 1:.*?(\d+)', response, re.IGNORECASE)
        if match:
            idx = int(match.group(1))
            if 0 <= idx < len(current_themes):
                return current_themes[idx]['theme'], sentiment
        return "Uncategorized", sentiment
    except Exception:
        return "Error", sentiment


total_rows = len(df)
print(f"Processing all {total_rows} articles automatically...")

df[['theme', 'sentiment_group']] = df.progress_apply(
    lambda x: pd.Series(label_with_sentiment_context(x)), axis=1
)


df.to_csv('FINAL_RAISE_DATA.csv', index=False)

summary_counts = df.groupby(['sentiment_group', 'theme']).size().reset_index(name='article_count')
summary_counts.to_csv('THEME_SUMMARY_COUNTS.csv', index=False)

print("\n Done:")
print(f"Full data saved to: FINAL_RAISE_DATA.csv")
print(f"Summary counts saved to: THEME_SUMMARY_COUNTS.csv")
print("\nFinal Theme Distribution:")
print(df['theme'].value_counts())

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import textwrap

df_counts = pd.read_csv('THEME_SUMMARY_COUNTS.csv')
df_report = pd.read_csv('AI_NARRATIVE_REPORT.csv')

df_merged = pd.merge(df_counts, df_report, on=['theme', 'sentiment_group'], how='left')


df_narratives = df_merged.dropna(subset=['description']).copy()


def create_label(row):
    wrapped_desc = textwrap.fill(row['description'], width=60)
    return f"{row['theme']}\n({wrapped_desc})"

df_narratives['display_label'] = df_narratives.apply(create_label, axis=1)

plt.figure(figsize=(14, 12))
sns.set_style("whitegrid")


custom_palette = {
    'Negative': '#e74c3c',  # Red
    'Positive': '#3498db',  # Blue
    'Other': '#95a5a6',     # Grey
    'Neutral': '#95a5a6'    # Grey
}


df_sorted = df_narratives.sort_values('article_count', ascending=False)

plot = sns.barplot(
    data=df_sorted,
    y='display_label',
    x='article_count',
    hue='sentiment_group',
    palette=custom_palette,
    dodge=False
)

plt.title('AI Impact: Narrative Distribution & Definitions', fontsize=20, fontweight='bold', pad=25)
plt.xlabel('Number of Articles', fontsize=14)
plt.ylabel('', fontsize=12)
plt.legend(title='Sentiment Group', loc='lower right', fontsize=12)

plt.yticks(fontsize=10)

for container in plot.containers:
    plot.bar_label(container, padding=5, fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig('AI_Narrative_Impact_Report.png', dpi=300)
print("Narrative Report Chart saved as 'AI_Narrative_Impact_Report.png'")
plt.show()

import pandas as pd
from ollama import chat
from pydantic import BaseModel
import os

class LocationInfo(BaseModel):
    city: str | None
    state_region: str | None
    country: str | None

def ollama_pinpoint_light(row):
    prompt = f"""
    Identify the PRIMARY geographic location where the news events are actually taking place.

    TITLE: {row['title']}
    LINK/URL: {row['link']}

    GUIDELINES:
    1. Look for location keywords in the Title and the URL path (e.g., /uk/, /california/, /paris/).
    2. Focus on the SUBJECT of the story, not where the website is based.
    3. If it is a global story with no specific location, return 'Global' for country.
    4. If no specific city is mentioned, return the Country.
    """
    try:
        response = chat(
            model='llama3.2',
            messages=[{'role': 'user', 'content': prompt}],
            format=LocationInfo.model_json_schema(),
            options={'temperature': 0}
        )
        data = LocationInfo.model_validate_json(response.message.content)
        return [data.city, data.state_region, data.country]
    except:
        return [None, None, None]

input_file = 'FILTERED_EMOTION_DATA.csv'
output_file = 'ollama_location_results_LIGHT.csv'

df = pd.read_csv(input_file)

if os.path.exists(output_file):
    processed_df = pd.read_csv(output_file)
    start_index = len(processed_df)
    print(f"Resuming from row {start_index}...")
else:
    df['city'] = None
    df['state_region'] = None
    df['country'] = None
    start_index = 0

batch_size = 100
total_rows = len(df)

print(f"Starting Title+Link pinpointing for {total_rows} rows...")

for i in range(start_index, total_rows):
    location = ollama_pinpoint_light(df.iloc[i])
    df.at[i, 'city'] = location[0]
    df.at[i, 'state_region'] = location[1]
    df.at[i, 'country'] = location[2]

    if (i + 1) % 10 == 0 or i == total_rows - 1:
        print(f"Progress: {i+1}/{total_rows} ({((i+1)/total_rows)*100:.1f}%)", end='\r')

    if (i + 1) % batch_size == 0 or i == total_rows - 1:
        df.iloc[:i+1].to_csv(output_file, index=False)
        print(f"\n--- Checkpoint saved at row {i+1} ---")

print("\nLocation data is ready in 'ollama_location_results_LIGHT.csv'.")

import pandas as pd


loc_df = pd.read_csv('ollama_location_results_LIGHT.csv')
sent_df = pd.read_csv('SENTIMENT_DATA.csv')


df = pd.merge(
    loc_df,
    sent_df[['title', 'link', 'sentiment', 'source', 'month', 'year', 'classes_str']],
    on=['title', 'link'],
    how='left'
)


df['country'] = df['country'].fillna('Unknown')
df['sentiment'] = df['sentiment'].fillna('Neutral')


df_sorted = df.sort_values(
    by=['country', 'sentiment'],
    ascending=[True, False]
).copy()

df_sorted['is_country_start'] = df_sorted['country'] != df_sorted['country'].shift(1)


output_file = 'ORGANIZED_ARTICLES_BY_REGION.csv'
df_sorted.to_csv(output_file, index=False)


print(f"Successfully unified {len(df_sorted)} articles.")
print("\nTOP 5 COUNTRIES BY TOTAL VOLUME:")
print(df_sorted['country'].value_counts().head(5))

print(f"\nSaved Master File to: {output_file}")

import pandas as pd
import ollama
from tqdm import tqdm

region_df = pd.read_csv('ORGANIZED_ARTICLES_BY_REGION.csv')
enriched_df = pd.read_csv('ENRICHED_NEWS_DATA.csv')

df = pd.merge(
    region_df[['title', 'link', 'country', 'sentiment']],
    enriched_df[['title', 'link', 'one_sentence_summary']],
    on=['title', 'link'],
    how='left'
)

def generate_narrative(summaries, sentiment, country):
    count = len(summaries)
    if count == 0: return None

    limit = min(count, 3)
    text_blob = "\n- ".join(summaries[:5])

    prompt = f"""
    [INST]
    Review these {sentiment} AI news summaries for {country}:
    {text_blob}
    TASK: Write a {sentiment} narrative for AI developments in {country}.
    CONSTRAINTS: Exactly {limit} sentence(s) long. No filler.
    [/INST]
    """

    try:
        res = ollama.chat(model='llama3.2', messages=[{'role': 'user', 'content': prompt}], options={'temperature': 0.1})
        return res['message']['content'].strip()
    except:
        return None

results = []
clean_df = df[(df['country'] != 'Unknown') & (df['sentiment'].isin(['Positive', 'Negative']))]

groups = clean_df.groupby(['country', 'sentiment'], sort=False)

print(f"Generating narratives following specific regional order...")

for (country, sentiment), group in tqdm(groups):
    summaries = group['one_sentence_summary'].dropna().tolist()

    if len(summaries) > 0:
        narrative = generate_narrative(summaries, sentiment, country)
        if narrative:
            results.append({
                'country': country,
                'sentiment': sentiment,
                'article_count': len(summaries),
                'narrative': narrative
            })

narrative_df = pd.DataFrame(results)
narrative_df.to_csv('GLOBAL_AI_NARRATIVES.csv', index=False)

print("\nSaved to 'GLOBAL_AI_NARRATIVES.csv'")

import pandas as pd
import ollama

df = pd.read_csv('GLOBAL_AI_NARRATIVES.csv')

def find_global_themes(sentiment):
    narratives = df[df['sentiment'] == sentiment]['narrative'].dropna().tolist()
    all_text = "\n---\n".join(narratives)

    prompt = f"""
    [INST]
    You are a global trend researcher. Below is a collection of {sentiment} AI narratives from many different countries.

    TASK:
    Identify the TOP 5 RECURRING THEMES that appear across these different countries.

    NARRATIVES:
    {all_text}

    RULES:
    1. THE FOCUS: Focus on the 'Core Concern' or 'Core Benefit' that appears in multiple regions.
    2. SUMMARIZATION: For each of the 5 themes, provide a 1-2 sentence explanation of the narrative.
    3. AVOID BROAD BUCKETS: Do not use 'Ethics', 'General Progress', 'Regulation', or 'Innovation'.
    4. THE SWEET SPOT: Themes must be specific enough to describe a real problem/benefit (e.g., 'Replacement of entry-level administrative roles') but general enough to apply to multiple different companies/locations.
    5. NO PROPER NOUNS: No names of companies, cities, or specific people.
    6. HUMAN-CENTRIC: Focus on how a person's life, job, or safety changes.
    7. Return ONLY the 5 themes.
    [/INST]
    """

    try:
        res = ollama.chat(model='llama3.2', messages=[{'role': 'user', 'content': prompt}], options={'temperature': 0.1})
        return res['message']['content'].strip()
    except:
        return "Error analyzing themes."

print("Analyzing all countries to find Universal Positive Themes...")
universal_positive = find_global_themes('Positive')

print("Analyzing all countries to find Universal Negative Themes...")
universal_negative = find_global_themes('Negative')

print("\n" + "="*60)
print("TOP 5 GLOBAL POSITIVE THEMES (Qualitative Analysis)")
print("="*60)
print(universal_positive)

print("\n" + "="*60)
print("TOP 5 GLOBAL NEGATIVE THEMES (Qualitative Analysis)")
print("="*60)
print(universal_negative)

with open('UNIVERSAL_AI_THEMES_REPORT.txt', 'w', encoding='utf-8') as f:
    f.write("UNIVERSAL AI THEMES REPORT\n")
    f.write("="*30 + "\n\n")
    f.write("POSITIVE THEMES:\n" + universal_positive + "\n")
    f.write("NEGATIVE THEMES:\n" + universal_negative + "\n")

print(f"\nReport saved to 'UNIVERSAL_AI_THEMES_REPORT.txt'")

import pandas as pd
import ollama
import json
import re
from tqdm import tqdm

def get_full_context_from_txt(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    pos_defs, neg_defs, current_section, current_block = [], [], None, ""
    for line in lines:
        clean_line = line.strip()
        if "POSITIVE THEMES" in clean_line.upper(): current_section = "pos"; continue
        elif "NEGATIVE THEMES" in clean_line.upper():
            if current_block: pos_defs.append(current_block.strip())
            current_block = ""; current_section = "neg"; continue
        if re.match(r"^\d+\.", clean_line):
            if current_block:
                if current_section == "pos": pos_defs.append(current_block.strip())
                else: neg_defs.append(current_block.strip())
            current_block = clean_line
        else:
            if clean_line: current_block += " " + clean_line
    if current_block:
        if current_section == "pos": pos_defs.append(current_block.strip())
        else: neg_defs.append(current_block.strip())
    return pos_defs[:5], neg_defs[:5]

def get_clean_title(text):
    clean = re.sub(r"^\d+\.\s*", "", text).replace("*", "")
    return clean.split(":")[0].strip()

pos_defs, neg_defs = get_full_context_from_txt('UNIVERSAL_AI_THEMES_REPORT.txt')
pos_titles = [get_clean_title(d) for d in pos_defs]
neg_titles = [get_clean_title(d) for d in neg_defs]

def classify_ranked_best_fit(narrative, titles, full_definitions):
    if pd.isna(narrative) or not titles: return []

    prompt = f"""
    [INST]
    Analyze the following AI narrative and determine which theme from the list below is the best match.

    VALID THEME TITLES:
    {titles}

    DETAILED THEME DEFINITIONS:
    {full_definitions}

    COUNTRY NARRATIVE:
    "{narrative}"

    TASK:
    1. Identify the top 3 most relevant titles from the VALID THEME TITLES list.
    2. Compare these 3 and select the SINGLE best fit based on the detailed definitions.

    RULES:
    1. The "best_fit" MUST be one of the exact titles from the list provided.
    2. Do not use generic labels like "Theme 1" or "Option A".
    3. If no theme fits well, return null for best_fit.

    Return ONLY a JSON object: {{"top_3_candidates": ["Title1", "Title2", "Title3"], "best_fit": "TitleName"}}
    [/INST]
    """
    try:
        res = ollama.chat(model='llama3.2', messages=[{'role': 'user', 'content': prompt}], format='json', options={'temperature': 0})
        data = json.loads(res['message']['content'])
        choice = data.get('best_fit', "")

        for t in titles:
            if t.lower() in str(choice).lower():
                return [t]
        return []
    except:
        return []

df_narratives = pd.read_csv('GLOBAL_AI_NARRATIVES.csv')
results = []

print("Ranking top 3 and enforcing strict title selection...")
for _, row in tqdm(df_narratives.iterrows(), total=len(df_narratives)):
    target_titles = pos_titles if row['sentiment'] == 'Positive' else neg_titles
    target_defs = pos_defs if row['sentiment'] == 'Positive' else neg_defs

    matches = classify_ranked_best_fit(row['narrative'], target_titles, target_defs)

    for theme in matches:
        results.append({'country': row['country'], 'sentiment': row['sentiment'], 'theme': theme})

if results:
    final_df = pd.DataFrame(results)
    summary = final_df.groupby(['sentiment', 'theme']).size().reset_index(name='country_count')
    summary.to_csv('FINAL_THEME_FREQUENCIES.csv', index=False)
    print("\nThemes ranked and best-fit labels enforced.")
    print(summary.sort_values(by=['sentiment', 'country_count'], ascending=[True, False]))

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import textwrap
import re

def get_themes_from_txt(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    data, current_sentiment, current_theme, current_desc = [], None, None, []
    for line in lines:
        clean_line = line.strip()
        if not clean_line: continue
        if "POSITIVE THEMES" in clean_line.upper():
            current_sentiment = "Positive"; continue
        elif "NEGATIVE THEMES" in clean_line.upper():
            current_sentiment = "Negative"; continue
        theme_start = re.match(r"^(\d+[\.\)]|\*+)\s*(.*)", clean_line)
        if theme_start and current_sentiment:
            if current_theme:
                data.append({'theme': current_theme, 'description': " ".join(current_desc), 'sentiment_group': current_sentiment})
            raw_title = theme_start.group(2)
            if ":" in raw_title:
                parts = raw_title.split(":", 1)
                current_theme = parts[0].strip().replace('*', '')
                current_desc = [parts[1].strip()]
            else:
                current_theme = raw_title.strip().replace('*', '')
                current_desc = []
        else:
            if current_theme: current_desc.append(clean_line)
    if current_theme:
        data.append({'theme': current_theme, 'description': " ".join(current_desc), 'sentiment_group': current_sentiment})
    return pd.DataFrame(data)

df_report = get_themes_from_txt('UNIVERSAL_AI_THEMES_REPORT.txt')
df_counts = pd.read_csv('FINAL_THEME_FREQUENCIES.csv')
df_counts = df_counts.rename(columns={'sentiment': 'sentiment_group'})
df_merged = pd.merge(df_counts, df_report, on=['theme', 'sentiment_group'], how='left')

def create_full_label(row):
    theme_name = str(row['theme']).upper()
    desc = str(row['description']).replace('nan', '').strip()

    if len(desc) < 5:
        return theme_name

    wrapped_desc = textwrap.fill(desc, width=65)
    return f"{theme_name}\n{wrapped_desc}"

df_merged['display_label'] = df_merged.apply(create_full_label, axis=1)

plt.figure(figsize=(16, 20))
sns.set_style("whitegrid")
custom_palette = {'Negative': '#e74c3c', 'Positive': '#3498db'}

df_sorted = df_merged.sort_values('country_count', ascending=False)

plot = sns.barplot(
    data=df_sorted,
    y='display_label',
    x='country_count',
    hue='sentiment_group',
    palette=custom_palette,
    dodge=False
)

plt.title('Global AI Narratives: Full Thematic Reach', fontsize=22, fontweight='bold', pad=30)
plt.xlabel('Number of Countries Representing Theme', fontsize=14)
plt.ylabel('')

plt.yticks(fontsize=9, family='monospace')

plt.legend(title='Sentiment', loc='lower right', fontsize=12)

for container in plot.containers:
    plot.bar_label(container, padding=10, fontsize=12, fontweight='bold')

plt.tight_layout(pad=3.0)
plt.savefig('FULL_DESCRIPTION_THEME_CHART.png', dpi=300)
plt.show()

print(f"Full Description Chart saved with {len(df_report)} themes.")

import pandas as pd
import plotly.express as px
import numpy as np


df_combined = pd.read_csv('ORGANIZED_ARTICLES_BY_REGION.csv')

df_combined = df_combined[df_combined['country'].str.lower() != 'global']


COORDS = {
    'New York': [40.71, -74.00], 'Los Angeles': [34.05, -118.24], 'Chicago': [41.87, -87.62],
    'San Francisco': [37.77, -122.41], 'Boston': [42.36, -71.05], 'Seattle': [47.60, -122.33],
    'Washington': [38.90, -77.03], 'London': [51.50, -0.12], 'Paris': [48.85, 2.35], 'Berlin': [52.52, 13.40],
    'Tokyo': [35.67, 139.65], 'Beijing': [39.90, 116.40], 'Singapore': [1.35, 103.81], 'Seoul': [37.56, 126.97],
    'Mumbai': [19.07, 72.87], 'Sydney': [-33.86, 151.20], 'Toronto': [43.65, -79.38],
    'Texas': [31.00, -100.00], 'California': [36.78, -119.42], 'Florida': [27.66, -81.52],
    'United States': [37.09, -95.71], 'United States of America': [37.09, -95.71],
    'China': [35.86, 104.19], 'India': [20.59, 78.96],
    'UK': [55.37, -3.43], 'Germany': [51.16, 10.45], 'France': [46.22, 2.21], 'Canada': [56.13, -106.34],
    'Australia': [-25.27, 133.77],
    'Global': [0, 0]
}

def get_coords(row, coord_type):
    location_name = row['city']
    if pd.notna(location_name):
        coords = COORDS.get(location_name)
        if coords:
            return coords[0] if coord_type == 'lat' else coords[1]

    location_name = row['country']
    if pd.notna(location_name):
        coords = COORDS.get(location_name)
        if coords:
            return coords[0] if coord_type == 'lat' else coords[1]

    return np.nan

df_combined['base_lat'] = df_combined.apply(lambda row: get_coords(row, 'lat'), axis=1)
df_combined['base_lon'] = df_combined.apply(lambda row: get_coords(row, 'lon'), axis=1)



df_combined.dropna(subset=['base_lat', 'base_lon'], inplace=True)

df_shuffled = df_combined.sample(frac=1).reset_index(drop=True)

def apply_horizontal_organic_spacing(group):
    n = len(group)
    if n == 0: return group

    base_lat = group['base_lat'].iloc[0]
    base_lon = group['base_lon'].iloc[0]


    v_tightness = 0.3
    h_stretch = 0.7

    indices = np.arange(n)

    random_angles = np.random.uniform(0, 2 * np.pi, n)

    r = np.sqrt(indices + 1)

    group['final_lat'] = base_lat + (v_tightness * r * np.sin(random_angles))
    group['final_lon'] = base_lon + (h_stretch * r * np.cos(random_angles))

    return group

df_final = df_shuffled.groupby('country', group_keys=False).apply(apply_horizontal_organic_spacing)

fig = px.scatter_geo(
    df_final,
    lat="final_lat",
    lon="final_lon",
    color="sentiment",
    hover_name="title",
    hover_data={'country': True, 'sentiment': True},
    title="Global AI Sentiment: Horizontal Cluster Analysis",
    color_discrete_map={'Positive': '#3498db', 'Negative': '#e74c3c', 'Neutral': '#95a5a6'},
    opacity=0.85,
    projection="natural earth"
)

fig.update_geos(
    showland=True, landcolor="white",
    showcountries=True, countrycolor="#dfe6e9",
    showocean=True, oceancolor="#f0f2f5",
    lakecolor="#f0f2f5"
)

fig.update_layout(
    height=800,
    margin={"r":0,"t":50,"l":0,"b":0},
    legend=dict(orientation="h", y=0.05, x=0.5, xanchor="center")
)

fig.show()

"""**Raise All Topics Map**"""

import pandas as pd
import plotly.graph_objects as go
import numpy as np
import os
import re
from collections import Counter
from geopy.geocoders import ArcGIS
from geopy.extra.rate_limiter import RateLimiter
import time

print("📡 Initializing Dashboard with Dataset A...")

COORDS = {
    'New York': [40.71, -74.00], 'Los Angeles': [34.05, -118.24], 'Chicago': [41.87, -87.62],
    'San Francisco': [37.77, -122.41], 'Boston': [42.36, -71.05], 'Seattle': [47.60, -122.33],
    'Washington': [38.90, -77.03], 'London': [51.50, -0.12], 'Paris': [48.85, 2.35], 'Berlin': [52.52, 13.40],
    'Tokyo': [35.67, 139.65], 'Beijing': [39.90, 116.40], 'Singapore': [1.35, 103.81], 'Seoul': [37.56, 126.97],
    'Mumbai': [19.07, 72.87], 'Sydney': [-33.86, 151.20], 'Toronto': [43.65, -79.38],
    'Texas': [31.00, -100.00], 'California': [36.78, -119.42], 'Florida': [27.66, -81.52],
    'United States': [37.09, -95.71], 'China': [35.86, 104.19], 'India': [20.59, 78.96],
    'UK': [55.37, -3.43], 'Germany': [51.16, 10.45], 'France': [46.22, 2.21], 'Canada': [56.13, -106.34]
}

CATEGORY_MAP = {
    'Emotion & Wellbeing (Pink)': {'color': '#FF00FF', 'keywords': ['emotion', 'motivation', 'well-being', 'wellbeing', 'sentiment', 'stress', 'fear', 'anxiety']},
    'Society & Roles (Yellow)': {'color': '#FFFF00', 'keywords': ['roles', 'interaction', 'relationships', 'social', 'society', 'ethics', 'culture', 'governance', 'privacy']},
    'Work & Lifestyle (Green)': {'color': '#00FF00', 'keywords': ['routine', 'lifestyle', 'behavior', 'work', 'jobs', 'economy', 'productivity', 'automation']},
    'Health & Cognition (Cyan)': {'color': '#00FFFF', 'keywords': ['cognitive', 'decision', 'reasoning', 'health', 'safety', 'risk', 'medical']},
    'Innovation & Knowledge (Orange)': {'color': '#FF9900', 'keywords': ['creativity', 'expression', 'identity', 'learning', 'knowledge', 'education', 'technology', 'digital']}
}

def get_shared_context(titles1, titles2):
    words1 = set(re.findall(r'\w+', " ".join(titles1).lower()))
    words2 = set(re.findall(r'\w+', " ".join(titles2).lower()))
    stop = {'the', 'and', 'for', 'with', 'from', 'this', 'that', 'ai', 'impact', 'using', 'report', 'research'}
    common = [w for w in words1.intersection(words2) if len(w) > 4 and w not in stop]
    return ", ".join(common[:3])

dc_traces = []
dc_path = "/content/data_centers_global.csv"
if os.path.exists(dc_path):
    print(" Geocoding Infrastructure with ArcGIS...")
    dc_df = pd.read_csv(dc_path).groupby(['City', 'Country']).agg({'Total_Data_Centers': 'sum'}).reset_index()
    geolocator = ArcGIS(timeout=10)
    geocode = RateLimiter(geolocator.geocode, min_delay_seconds=0.1)
    lats, lons, texts = [], [], []
    for _, row in dc_df.iterrows():
        try:
            loc = geocode(f"{row['City']}, {row['Country']}")
            if loc:
                lats.append(loc.latitude); lons.append(loc.longitude)
                texts.append(f" <b>AI HUB</b><br>{row['City']}<br>Centers: {row['Total_Data_Centers']}")
        except: continue
    dc_traces.append(go.Scattermapbox(lat=lats, lon=lons, mode='markers', marker=dict(size=8, color='white'), text=texts, hoverinfo='text', name='🏢 AI Infrastructure'))

print(" Loading Dataset A...")
df = pd.read_csv("/content/dataset_A_news_full_10500.csv")

map_counts = {}

for _, row in df.iterrows():
    title = str(row.get('title', '')).lower()
    matched_loc = next((l for l in COORDS if l.lower() in title), None)
    if matched_loc:
        classes = str(row.get('classes_str', '')).lower()
        group = next((g for g, info in CATEGORY_MAP.items() if any(kw in classes for kw in info['keywords'])), None)
        if group:
            if matched_loc not in map_counts:
                map_counts[matched_loc] = {'coords': COORDS[matched_loc], 'groups': {}, 'titles': []}
            map_counts[matched_loc]['groups'][group] = map_counts[matched_loc]['groups'].get(group, 0) + 1
            map_counts[matched_loc]['titles'].append(str(row['title']))

bridge_lat, bridge_lon = [], []
mid_lat, mid_lon, mid_text = [], [], []
cities = list(map_counts.keys())

for i in range(len(cities)):
    for j in range(i + 1, len(cities)):
        t1, t2 = map_counts[cities[i]]['titles'], map_counts[cities[j]]['titles']
        shared = get_shared_context(t1, t2)
        if shared:
            c1, c2 = map_counts[cities[i]]['coords'], map_counts[cities[j]]['coords']
            bridge_lat.extend([c1[0], c2[0], None])
            bridge_lon.extend([c1[1], c2[1], None])
            m_lat, m_lon = (c1[0] + c2[0]) / 2, (c1[1] + c2[1]) / 2
            mid_lat.append(m_lat); mid_lon.append(m_lon)
            mid_text.append(f"⛓️ <b>Knowledge Bridge</b><br>{cities[i]} ↔ {cities[j]}<br>Shared Focus: <i>{shared}</i>")

bridge_trace = go.Scattermapbox(
    lat=bridge_lat, lon=bridge_lon, mode='lines',
    line=dict(width=1, color='rgba(100, 200, 255, 0.2)'),
    hoverinfo='none', name='Knowledge Bridges', visible='legendonly'
)

hover_bridge_trace = go.Scattermapbox(
    lat=mid_lat, lon=mid_lon, mode='markers',
    marker=dict(size=10, color='rgba(0,0,0,0)'),
    text=mid_text, hoverinfo='text', name='Bridge Details', visible='legendonly'
)

article_traces = []
offset_angles = [0, 72, 144, 216, 288]
for idx, (group_name, info) in enumerate(CATEGORY_MAP.items()):
    lats, lons, texts, sizes = [], [], [], []
    angle = offset_angles[idx % 5]
    for loc, data in map_counts.items():
        if group_name in data['groups']:
            count = data['groups'][group_name]
            off_lat = 0.3 * np.cos(np.radians(angle)) if len(data['groups']) > 1 else 0
            off_lon = 0.3 * np.sin(np.radians(angle)) if len(data['groups']) > 1 else 0
            lats.append(data['coords'][0] + off_lat); lons.append(data['coords'][1] + off_lon)
            texts.append(f"<b>{group_name}</b><br>📍 {loc}<br>Count: {count}")
            sizes.append(np.log1p(count) * 11 + 6)
    if lats:
        article_traces.append(go.Scattermapbox(lat=lats, lon=lons, mode='markers', marker=dict(size=sizes, color=info['color'], opacity=0.7), text=texts, hoverinfo='text', name=group_name))

fig = go.Figure(data=[bridge_trace, hover_bridge_trace] + dc_traces + article_traces)

fig.update_layout(
    mapbox_style='carto-darkmatter', mapbox={'center': {'lat': 20, 'lon': 0}, 'zoom': 1.2},
    margin={'r': 0, 't': 50, 'l': 0, 'b': 0}, paper_bgcolor='#1a1a1a',
    title={'text': 'RAISE-26 DASHBOARD // Bridges, Infra & Dataset A', 'font': {'color': 'white', 'size': 24}, 'x': 0.5},
    legend={'font': {'color': 'white'}, 'bgcolor': 'rgba(0,0,0,0.6)', 'x': 0, 'y': 0}
)

fig.show()